let
    Source = File.Contents("INSERT_YOUR_FILEPATH_HERE"),
        Files = UnzipContents(Source),
    Content = Files{0}[Content],
    #"Imported CSV" = Csv.Document(Content,[Delimiter="|", Columns=41, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Removed Top Row" = Table.Skip(#"Imported CSV",1),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Row", [PromoteAllScalars=true]),
    #"Trimmed Text" = Table.TransformColumns(#"Promoted Headers",{{"CURRENT_RUN_DATE_QBE", Text.Trim, type text}, {"SITE_ID", Text.Trim, type text}, {"FUND", Text.Trim, type text}, {"OE", Text.Trim, type text}, {"OAC", Text.Trim, type text}, {"OBAN", Text.Trim, type text}, {"DEPARTMENT", Text.Trim, type text}, {"MAIN_ACCOUNT", Text.Trim, type text}, {"SUBHEAD", Text.Trim, type text}, {"LIMIT", Text.Trim, type text}, {"POA", Text.Trim, type text}, {"COST_CENTER", Text.Trim, type text}, {"OC", Text.Trim, type text}, {"SALES_CODE", Text.Trim, type text}, {"ESP", Text.Trim, type text}, {"PROGRAM", Text.Trim, type text}, {"AAI", Text.Trim, type text}, {"LOB", Text.Trim, type text}, {"WON_JON", Text.Trim, type text}, {"BL", Text.Trim, type text}, {"BA", Text.Trim, type text}, {"BSA", Text.Trim, type text}, {"BLI", Text.Trim, type text}, {"REIM_FLAG", Text.Trim, type text}, {"COM", Text.Trim, type text}, {"UOO", Text.Trim, type text}, {"AEU", Text.Trim, type text}, {"AEP", Text.Trim, type text}, {"ADVANCE_PAYMENTS", Text.Trim, type text}, {"DOC_ID", Text.Trim, type text}, {"DOCUMENT_CREATION_DATE_QBE", Text.Trim, type text}, {"TOTAL_PAYABLES", Text.Trim, type text}, {"FIRST_DAY_TRAVEL_QBE", Text.Trim, type text}, {"LAST_DAY_TRAVEL_QBE", Text.Trim, type text}, {"ORDER_TYPE", Text.Trim, type text}, {"TRAVEL_ORDER", Text.Trim, type text}, {"PERFORM_FCFY", Text.Trim, type text}, {"TRAVELER_NAME", Text.Trim, type text}, {"SUPPLIER_NUMBER", Text.Trim, type text}, {"APPROVAL_STATUS", Text.Trim, type text}, {"DAYS_OLD", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"CURRENT_RUN_DATE_QBE", Text.Clean, type text}, {"SITE_ID", Text.Clean, type text}, {"FUND", Text.Clean, type text}, {"OE", Text.Clean, type text}, {"OAC", Text.Clean, type text}, {"OBAN", Text.Clean, type text}, {"DEPARTMENT", Text.Clean, type text}, {"MAIN_ACCOUNT", Text.Clean, type text}, {"SUBHEAD", Text.Clean, type text}, {"LIMIT", Text.Clean, type text}, {"POA", Text.Clean, type text}, {"COST_CENTER", Text.Clean, type text}, {"OC", Text.Clean, type text}, {"SALES_CODE", Text.Clean, type text}, {"ESP", Text.Clean, type text}, {"PROGRAM", Text.Clean, type text}, {"AAI", Text.Clean, type text}, {"LOB", Text.Clean, type text}, {"WON_JON", Text.Clean, type text}, {"BL", Text.Clean, type text}, {"BA", Text.Clean, type text}, {"BSA", Text.Clean, type text}, {"BLI", Text.Clean, type text}, {"REIM_FLAG", Text.Clean, type text}, {"COM", Text.Clean, type text}, {"UOO", Text.Clean, type text}, {"AEU", Text.Clean, type text}, {"AEP", Text.Clean, type text}, {"ADVANCE_PAYMENTS", Text.Clean, type text}, {"DOC_ID", Text.Clean, type text}, {"DOCUMENT_CREATION_DATE_QBE", Text.Clean, type text}, {"TOTAL_PAYABLES", Text.Clean, type text}, {"FIRST_DAY_TRAVEL_QBE", Text.Clean, type text}, {"LAST_DAY_TRAVEL_QBE", Text.Clean, type text}, {"ORDER_TYPE", Text.Clean, type text}, {"TRAVEL_ORDER", Text.Clean, type text}, {"PERFORM_FCFY", Text.Clean, type text}, {"TRAVELER_NAME", Text.Clean, type text}, {"SUPPLIER_NUMBER", Text.Clean, type text}, {"APPROVAL_STATUS", Text.Clean, type text}, {"DAYS_OLD", Text.Clean, type text}}),
    #"Added PEC Column" = Table.AddColumn(#"Cleaned Text", "PEC", each if [PROGRAM]="NA#(tab)" then "NA" else Text.Range([PROGRAM],1,1)&Text.Range([PROGRAM],3,5)),
    #"Added Report Date Column" = Table.AddColumn(#"Added PEC Column", "Report Date", each Date.From(DateTime.From([CURRENT_RUN_DATE_QBE], "en-us"))),
    #"Added Doc Creation Column" = Table.AddColumn(#"Added Report Date Column", "Document Creation Date", each Date.From(DateTime.From([DOCUMENT_CREATION_DATE_QBE], "en-us"))),
    #"Added First Travel Day Column" = Table.AddColumn(#"Added Doc Creation Column", "First Travel Day", each if [FIRST_DAY_TRAVEL_QBE] = null then " " else Date.From(DateTime.From([FIRST_DAY_TRAVEL_QBE], "en-us"))),
    #"Added Last Travel Day Column" = Table.AddColumn(#"Added First Travel Day Column", "Last Travel Day", each Date.From(DateTime.From([LAST_DAY_TRAVEL_QBE], "en-us"))),
    #"Added ObjSubClass Column" = Table.AddColumn(#"Added Last Travel Day Column", "Object SubClass", each Text.Start([OC],3)&Text.End([OC],4)),
    #"Removed Columns" = Table.RemoveColumns(#"Added ObjSubClass Column",{"CURRENT_RUN_DATE_QBE", "SITE_ID", "OAC", "OBAN", "DEPARTMENT", "SUBHEAD", "LIMIT", "AAI", "LOB", "WON_JON", "ADVANCE_PAYMENTS", "DOCUMENT_CREATION_DATE_QBE", "FIRST_DAY_TRAVEL_QBE", "LAST_DAY_TRAVEL_QBE", "PROGRAM", "TOTAL_PAYABLES", "PERFORM_FCFY", "BL", "OC", "SALES_CODE"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"FUND", "Fund"}, {"MAIN_ACCOUNT", "Appropriation"}, {"POA", "FY"}, {"COST_CENTER", "RCCC"}, {"REIM_FLAG", "Reimbursement Flag"}, {"DOC_ID", "Document ID"}, {"ORDER_TYPE", "Order Type"}, {"TRAVEL_ORDER", "Travel Order"}, {"TRAVELER_NAME", "Traveler Name"}, {"SUPPLIER_NUMBER", "Supplier Number"}, {"APPROVAL_STATUS", "Approval Status"}, {"DAYS_OLD", "Days Old"}}),
    #"Replaced Value ESP" = Table.ReplaceValue(#"Renamed Columns","#","",Replacer.ReplaceText,{"ESP"}),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Replaced Value ESP", {{"First Travel Day", #date(1900, 1, 1)}, {"Last Travel Day", #date(1900, 1, 1)}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Errors",{{"COM", Currency.Type}, {"UOO", Currency.Type}, {"AEU", Currency.Type}, {"AEP", Currency.Type}, {"PEC", type text}, {"Report Date", type date}, {"Document Creation Date", type date}, {"First Travel Day", type date}, {"Last Travel Day", type date}, {"Object SubClass", type text}, {"Days Old", Int64.Type}}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type",{{"Traveler Name", Text.Proper, type text}}),
    #"Replaced Value 3700-RPA" = Table.ReplaceValue(#"Capitalized Each Word","3700","RPA",Replacer.ReplaceText,{"Appropriation"}),
    #"Replaced Value 3740-AFRC O&M" = Table.ReplaceValue(#"Replaced Value 3700-RPA","3740","O&M-AFRC",Replacer.ReplaceText,{"Appropriation"}),
    #"Replaced Value" = Table.ReplaceValue(#"Replaced Value 3740-AFRC O&M","3400","O&M-AD",Replacer.ReplaceText,{"Appropriation"}),
    #"Extracted First Characters from FY" = Table.TransformColumns(#"Replaced Value", {{"FY", each Text.Start(_, 2), type text}})
in
    #"Extracted First Characters from FY"
